

### Register
POST /auth/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "fullname": "John Doe",
  "username": "johndoe",
  "email": "john.doe@example.com",
  "password": "P@ssw0rd123!"
}

###
POST /auth/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "username": "john.doe@example.com",
  "password": "P@ssw0rd123!"
}